### ISSUE TITLE
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by millerh1** [Bishop-Laboratory/RLPipes#82]
Run into this problem when doing default bioconda install:

```shell
(base) millerh1@DESKTOP-D6G0FNB:~/RLPipes$ conda activate rlpipes2
(rlpipes2) millerh1@DESKTOP-D6G0FNB:~/RLPipes$ python
Python 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:37)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/millerh1/miniconda3/envs/rlpipes2/lib/python3.9/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```

For the bioconda install in a fresh env, it's using `pysam=0.9.1`

This is fixed by upgrading to `pysam=0.17.0`

```shell
(rlpipes2) millerh1@DESKTOP-D6G0FNB:~/RLPipes$ python
Python 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:11)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysam
>>>
```

Recommended fix: find and pin minimal version for bioconda recipe.

**Comment by millerh1** [comment]
Fixed by pinning reqs to `pysam>=0.17.0`
