### ISSUE TITLE
latency error

### ISSUE THREAD

**Issue by markdunning** [Bishop-Laboratory/RLPipes#90]
Hi again,

My rlpipes job managed to run successfully for a while, but now I am encountering an error

```
Activating conda environment: /mnt/fastdata/md1mjdx/INDUCESEQ_drip/rlpipes_out/.snakemake/conda/58e7a6e8fcc8d3c69ed54a6a4864418c
Activating conda environment: /mnt/fastdata/md1mjdx/INDUCESEQ_drip/rlpipes_out/.snakemake/conda/58e7a6e8fcc8d3c69ed54a6a4864418c
Waiting at most 3 seconds for missing files.
MissingOutputException in line 629 of /shared/bioinformatics_core1/Shared/software/miniconda3/envs/envs/rlpipes/lib/python3.9/site-packages/rlpipes/src/rlpipes.smk:
Job Missing files after 3 seconds:
/mnt/fastdata/md1mjdx/INDUCESEQ_drip/rlpipes_out/tmp/sras/SRX8956953/SRR12462633/SRR12462633.sra
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Job id: 13 completed successfully, but some output files are missing. 13
  File "/shared/bioinformatics_core1/Shared/software/miniconda3/envs/envs/rlpipes/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 584, in handle_job_success
  File "/shared/bioinformatics_core1/Shared/software/miniconda3/envs/envs/rlpipes/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 252, in handle_job_success
```

Based on the error, I tried to increase the latency-wait argument to snakemake with the following:-
(which I think is the correct way to specify snakemake arguments?)

```
RLPipes run -s "{'latency-wait': 50}" -t 4 rlpipes_out
```

But it is complaining that it doesn't know what latency-wait is:-

```
(base) [md1mjdx@sharc-login1 INDUCESEQ_drip]$ cat rlpipes.log 
Traceback (most recent call last):
  File "/shared/bioinformatics_core1/Shared/software/miniconda3/envs/envs/rlpipes/bin/RLPipes", line 10, in <module>
    sys.exit(cli())
  File "/shared/bioinformatics_core1/Shared/software/miniconda3/envs/envs/rlpipes/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/shared/bioinformatics_core1/Shared/software/miniconda3/envs/envs/rlpipes/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/shared/bioinformatics_core1/Shared/software/miniconda3/envs/envs/rlpipes/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/shared/bioinformatics_core1/Shared/software/miniconda3/envs/envs/rlpipes/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/shared/bioinformatics_core1/Shared/software/miniconda3/envs/envs/rlpipes/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/shared/bioinformatics_core1/Shared/software/miniconda3/envs/envs/rlpipes/lib/python3.9/site-packages/rlpipes/cli.py", line 635, in run
    exitcode = make_snakes(
  File "/shared/bioinformatics_core1/Shared/software/miniconda3/envs/envs/rlpipes/lib/python3.9/site-packages/rlpipes/run_workflow.py", line 106, in make_snakes
    good_exit = snk.snakemake(
TypeError: snakemake() got an unexpected keyword argument 'latency-wait'
```
Is this the correct way to increase the wait time?

Thanks

**Comment by millerh1** [comment]
Hi @markdunning -- I think it is unlikely that latency is responsible for the missing file issue. Can you share the log for that job? I suspect SRA prefetch may have failed part way through downloading the file.

**Comment by markdunning** [comment]
Hi, yes that could be the case that the download didn't work. I will try working from local fastq files since I have them anyway.

I'm still curious why setting the latency argument didn't work though?

**Comment by millerh1** [comment]
Can you share the log for that job? From your code, it appears you were using remote files, not local ones, for the run which failed. I would need additional information to diagnose though. 

The latency argument was not supplied correctly -- please refer to the snakemake python API for full list of available arguments: https://snakemake-api.readthedocs.io/en/latest/api_reference/snakemake.html

**Comment by markdunning** [comment]
I managed to fix the issue. It was a typo in the latency argument
